import {PGlite} from '@electric-sql/pglite';
import {before,after,test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
const db=new PGlite();
const a='10000000-0000-4000-8000-000000000001',b='20000000-0000-4000-8000-000000000001';
const ana='30000000-0000-4000-8000-000000000001',bia='30000000-0000-4000-8000-000000000002',lu='30000000-0000-4000-8000-000000000003',admin='40000000-0000-4000-8000-000000000001',staff='40000000-0000-4000-8000-000000000002',otherAdmin='40000000-0000-4000-8000-000000000003',superadmin='50000000-0000-4000-8000-000000000001';
let pregnancyA:string,pregnancyB:string;
async function as(uid:string|null,fn:(tx:{query:(sql:string,params?:any[])=>Promise<{rows:any[]}>})=>Promise<{rows:any[]}>,role='authenticated'):Promise<{rows:any[]}>{return db.transaction(async tx=>{await tx.exec(`set local role ${role}`);await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[uid||'']);return fn(tx);});}
async function rejects(uid:string|null,sql:string,params:unknown[]=[]){await assert.rejects(()=>as(uid,tx=>tx.query(sql,params)));}
before(async()=>{
 await db.exec(`create role anon nologin;create role authenticated nologin;create role service_role nologin bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb not null default '{}'::jsonb);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon;grant execute on function auth.uid() to authenticated,anon;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text);alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant select,insert,update,delete on storage.objects to authenticated;`);
 for(const name of (await readdir('supabase/migrations')).sort())await db.exec(await readFile('supabase/migrations/'+name,'utf8'));
 await db.exec(await readFile('supabase/seed.sql','utf8'));
 await db.exec('update private.registration_settings set enabled=true');
 const date=new Date(Date.now()+140*86400000).toISOString().slice(0,10);
 for(const [id,name,slug] of [[ana,'Ana Carolina','vida-plena'],[bia,'Beatriz','vida-plena'],[lu,'Luísa','clinica-horizonte']])await db.query('insert into auth.users(id,raw_user_meta_data) values($1,$2)',[id,JSON.stringify({full_name:name,clinic_slug:slug,due_date:date,terms_version:'2026-09-06',privacy_version:'2026-09-06',sensitive_consent:true,role:'clinic_admin',is_superadmin:true})]);
 for(const id of [admin,staff,otherAdmin,superadmin])await db.query("insert into auth.users(id,raw_user_meta_data) values($1,'{\"full_name\":\"Equipe fictícia\"}')",[id]);
 for(const [cid,uid,role] of [[a,admin,'clinic_admin'],[a,staff,'clinic_staff'],[b,otherAdmin,'clinic_admin']])await db.query('insert into public.clinic_memberships(clinic_id,user_id,role) values($1,$2,$3)',[cid,uid,role]);
 await db.query('insert into public.superadmins(user_id) values($1)',[superadmin]);
 pregnancyA=(await db.query<{id:string}>('select id from public.pregnancies where user_id=$1',[ana])).rows[0].id;
 pregnancyB=(await db.query<{id:string}>('select id from public.pregnancies where user_id=$1',[lu])).rows[0].id;
 await db.query("insert into public.private_memories(clinic_id,user_id,pregnancy_id,category,body) values($1,$2,$3,'diary','Privado de Ana'),($4,$5,$6,'diary','Privado de Luísa')",[a,ana,pregnancyA,b,lu,pregnancyB]);
 await db.query("insert into storage.objects(bucket_id,name) values('private-memories',$1)",[`${a}/${ana}/${pregnancyA}/imagem.png`]);
});
after(async()=>{await db.close();});
test('anonymous enrollment reads active plans including the ordering column',async()=>{const r=await as(null,tx=>tx.query('select code,name,price_cents,trial_days from public.access_plans where active order by months'),'anon');assert.ok(r.rows.some(p=>p.code==='monthly'));});
test('timeline combines birth and capsules without exposing another owner or tenant',async()=>{
 await db.exec("update public.feature_flags set enabled=true where key='postpartum'");
 const id=(await as(ana,tx=>tx.query("insert into private_memories(clinic_id,user_id,pregnancy_id,category,body,occurred_on,gestational_week) values($1,$2,$3,'letter','Guardado para depois',current_date-3,20) returning id",[a,ana,pregnancyA]))).rows[0].id;
 try {
  await as(ana,tx=>tx.query('insert into time_capsules(memory_id,user_id,opens_on) values($1,$2,current_date+20)',[id,ana]));
  await as(ana,tx=>tx.query("insert into birth_records(pregnancy_id,user_id,born_at,name) values($1,$2,now()-interval '1 day','Bebê de teste')",[pregnancyA,ana]));
  const list=(await as(ana,tx=>tx.query('select * from journey_timeline($1)',[a]))).rows;
  assert.ok(list.some(r=>r.id===pregnancyA&&r.category==='birth'));
  assert.ok(list.some(r=>r.id===id&&r.is_capsule));
  assert.deepEqual((await as(ana,tx=>tx.query("select id from journey_timeline($1,'capsule')",[a]))).rows,[{id}]);
  assert.equal((await as(ana,tx=>tx.query("select * from journey_timeline($1,'letter',20,current_date-3,current_date-3)",[a]))).rows.length,1);
  for(const u of [bia,admin,staff,otherAdmin,superadmin])assert.equal((await as(u,tx=>tx.query('select * from journey_timeline($1) where id in($2,$3)',[a,id,pregnancyA]))).rows.length,0);
  assert.equal((await as(ana,tx=>tx.query('select * from journey_timeline($1)',[b]))).rows.length,0);
  await assert.rejects(()=>as(null,tx=>tx.query('select * from journey_timeline($1)',[a]),'anon'));
  for(const oldest of [true,false]){
   const whole=(await as(ana,tx=>tx.query('select id from journey_timeline($1,null,null,null,null,$2)',[a,oldest]))).rows;
   const first=(await as(ana,tx=>tx.query('select id from journey_timeline($1,null,null,null,null,$2,0,1)',[a,oldest]))).rows;
   const rest=(await as(ana,tx=>tx.query('select id from journey_timeline($1,null,null,null,null,$2,1,100)',[a,oldest]))).rows;
   assert.deepEqual([...first,...rest],whole);
  }
  await db.exec("update public.feature_flags set enabled=false where key='postpartum'");
  assert.equal((await as(ana,tx=>tx.query("select * from journey_timeline($1,'birth')",[a]))).rows.length,0);
 } finally {
  await db.query('delete from public.birth_records where pregnancy_id=$1',[pregnancyA]);
  await db.query('delete from public.private_memories where id=$1',[id]);
  await db.exec("update public.feature_flags set enabled=false where key='postpartum'");
 }
});
test('all public tables have RLS enabled',async()=>{const {rows}=await db.query<{relname:string}>('select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname=\'public\' and c.relkind=\'r\' and not c.relrowsecurity');assert.deepEqual(rows,[]);});
test('anonymous cannot query clinic tables',async()=>{await assert.rejects(()=>as(null,tx=>tx.query('select * from public.clinics'),'anon'));});
test('public branding exposes only active clinic identity, never billing',async()=>{const {rows}=await as(null,tx=>tx.query("select public.get_public_clinic('vida-plena') as clinic"),'anon');assert.equal(rows[0].clinic.name,'Clínica Vida Plena');assert.ok(!('monthly_cents' in rows[0].clinic));assert.ok(!('plan_id' in rows[0].clinic));assert.equal(Object.keys(rows[0].clinic.tokens).length,12);});
test('registration ignores forged privilege metadata',async()=>{const {rows}=await as(ana,tx=>tx.query('select role from public.clinic_memberships'));assert.deepEqual(rows.map((x:any)=>x.role),['patient']);const s=await as(ana,tx=>tx.query('select * from public.superadmins'));assert.equal(s.rows.length,0);});
test('registration creates pregnancy and all versioned consents atomically',async()=>{const {rows}=await as(ana,tx=>tx.query('select * from public.consent_records'));assert.equal(rows.length,3);assert.ok(rows.every((x:any)=>x.user_id===ana&&x.clinic_id===a));});
test('invalid signup rolls back the auth user and profile',async()=>{const id='60000000-0000-4000-8000-000000000001';await assert.rejects(()=>db.query('insert into auth.users(id,raw_user_meta_data) values($1,$2)',[id,JSON.stringify({full_name:'Inválida',clinic_slug:'vida-plena'})]));assert.equal((await db.query('select * from auth.users where id=$1',[id])).rows.length,0);assert.equal((await db.query('select * from public.profiles where user_id=$1',[id])).rows.length,0);});
test('database gate blocks direct signup while enrollment is disabled',async()=>{await db.exec('update private.registration_settings set enabled=false');await assert.rejects(()=>db.query('insert into auth.users(id,raw_user_meta_data) values($1,$2)',['60000000-0000-4000-8000-000000000002',JSON.stringify({full_name:'Bloqueada',clinic_slug:'vida-plena'})]));await db.exec('update private.registration_settings set enabled=true');});
test('patient sees only own pregnancy, including within same clinic',async()=>{const {rows}=await as(ana,tx=>tx.query('select * from public.pregnancies'));assert.equal(rows.length,1);assert.equal(rows[0].user_id,ana);});
test('clinic staff can read operations only from their tenant',async()=>{for(const uid of [admin,staff]){const {rows}=await as(uid,tx=>tx.query('select * from public.pregnancies'));assert.equal(rows.length,2);assert.ok(rows.every((x:any)=>x.clinic_id===a));}});
test('other clinic admin only sees the other clinic',async()=>{const {rows}=await as(otherAdmin,tx=>tx.query('select * from public.pregnancies'));assert.equal(rows.length,1);assert.equal(rows[0].clinic_id,b);});
test('private memories hidden from same-clinic patients, team, admins and superadmin',async()=>{for(const uid of [bia,admin,staff,otherAdmin,superadmin])assert.equal((await as(uid,tx=>tx.query('select * from public.private_memories'))).rows.length,0);assert.equal((await as(ana,tx=>tx.query('select * from public.private_memories'))).rows.length,1);});
test('staff cannot read patient profiles or consent records',async()=>{assert.equal((await as(admin,tx=>tx.query('select * from public.profiles where user_id=$1',[ana]))).rows.length,0);assert.equal((await as(admin,tx=>tx.query('select * from public.consent_records'))).rows.length,0);});
test('forged memory owner and clinic/pregnancy relation are rejected',async()=>{await rejects(ana,"insert into public.private_memories(clinic_id,user_id,pregnancy_id,category) values($1,$2,$3,'diary')",[b,lu,pregnancyB]);await rejects(ana,"insert into public.private_memories(clinic_id,user_id,pregnancy_id,category) values($1,$2,$3,'diary')",[a,ana,pregnancyB]);});
test('patient cannot move memory to another owner',async()=>{await rejects(ana,'update public.private_memories set user_id=$1',[bia]);});
test('only clinic admin can change own theme and it persists',async()=>{for(const uid of [ana,staff,otherAdmin])assert.equal((await as(uid,tx=>tx.query("update public.clinic_themes set tokens=jsonb_set(tokens,'{primary}','\"#654333\"') where clinic_id=$1 returning *",[a]))).rows.length,0);const {rows}=await as(admin,tx=>tx.query("update public.clinic_themes set tokens=jsonb_set(tokens,'{primary}','\"#654333\"') where clinic_id=$1 returning *",[a]));assert.equal(rows.length,1);const read=await as(null,tx=>tx.query("select public.get_public_clinic('vida-plena') as clinic"),'anon');assert.equal(read.rows[0].clinic.tokens.primary,'#654333');});
test('invalid CSS injection and incomplete tokens are rejected in database',async()=>{await rejects(admin,"update public.clinic_themes set tokens=jsonb_set(tokens,'{primary}','\"red; background:url(https://bad.invalid)\"') where clinic_id=$1",[a]);await rejects(admin,"update public.clinic_themes set tokens='{}' where clinic_id=$1",[a]);});
test('theme clinic id cannot be changed',async()=>{await rejects(admin,'update public.clinic_themes set clinic_id=$1 where clinic_id=$2',[b,a]);});
test('no raw privilege escalation or consent tampering',async()=>{await rejects(ana,"update public.clinic_memberships set role='clinic_admin'");await rejects(ana,'insert into public.superadmins values($1)',[ana]);await rejects(ana,"update public.consent_records set version='forged'");await rejects(ana,"insert into public.audit_logs(action,entity) values('fake','fake')");});
test('staff role RPC refuses cross-tenant, self and patient conversion',async()=>{await rejects(admin,"select public.set_staff_membership($1,$2,'clinic_admin',true)",[b,staff]);await rejects(admin,"select public.set_staff_membership($1,$2,'clinic_admin',true)",[a,ana]);await rejects(admin,"select public.set_staff_membership($1,$2,'clinic_staff',true)",[a,admin]);await rejects(staff,"select public.set_staff_membership($1,$2,'clinic_admin',true)",[a,bia]);});
test('staff assignment works within authorized tenant',async()=>{await as(admin,tx=>tx.query("select public.set_staff_membership($1,$2,'clinic_staff',true)",[a,otherAdmin]));assert.equal((await as(otherAdmin,tx=>tx.query('select * from public.clinic_memberships where clinic_id=$1 and user_id=$2',[a,otherAdmin]))).rows.length,1);await db.query('delete from public.clinic_memberships where clinic_id=$1 and user_id=$2',[a,otherAdmin]);});
test('theme update generates audit without private payloads',async()=>{const {rows}=await as(admin,tx=>tx.query("select * from public.audit_logs where entity='clinic_themes' and action='UPDATE'"));assert.ok(rows.some((x:any)=>x.actor_id===admin&&x.clinic_id===a));assert.ok(!('tokens' in rows[0]));});
test('storage objects private to their owner including against superadmin',async()=>{for(const uid of [bia,admin,staff,otherAdmin,superadmin])assert.equal((await as(uid,tx=>tx.query('select * from storage.objects'))).rows.length,0);assert.equal((await as(ana,tx=>tx.query('select * from storage.objects'))).rows.length,1);await rejects(ana,"insert into storage.objects(bucket_id,name) values('private-memories',$1)",[`${b}/${lu}/${pregnancyB}/bad.png`]);});
test('suspension revokes current tenant access without relying on JWT role claims',async()=>{await db.query("update public.clinics set status='suspended' where id=$1",[a]);for(const uid of [ana,admin,staff]){assert.equal((await as(uid,tx=>tx.query('select * from public.pregnancies'))).rows.length,0);assert.equal((await as(uid,tx=>tx.query('select * from public.clinic_themes'))).rows.length,0);}assert.equal((await as(ana,tx=>tx.query('select * from storage.objects'))).rows.length,0);assert.equal((await as(null,tx=>tx.query("select public.get_public_clinic('vida-plena') as clinic"),'anon')).rows[0].clinic,null);await db.query("update public.clinics set status='active' where id=$1",[a]);});
test('revoked membership loses private access immediately',async()=>{await db.query('update public.clinic_memberships set active=false where clinic_id=$1 and user_id=$2',[a,ana]);assert.equal((await as(ana,tx=>tx.query('select * from public.private_memories'))).rows.length,0);assert.equal((await as(ana,tx=>tx.query('select * from public.my_clinic_links()'))).rows.length,0);await db.query('update public.clinic_memberships set active=true where clinic_id=$1 and user_id=$2',[a,ana]);});
test('superadmin can manage clinic status but cannot see patient operational records',async()=>{assert.equal((await as(superadmin,tx=>tx.query('select * from public.clinics'))).rows.length,2);assert.equal((await as(superadmin,tx=>tx.query('select * from public.pregnancies'))).rows.length,0);});
test('deleting an Auth user cascades profiles, pregnancies, consent and private memories',async()=>{await db.query('delete from auth.users where id=$1',[lu]);for(const table of ['profiles','clinic_memberships','pregnancies','consent_records','private_memories'])assert.equal((await db.query(`select * from public.${table} where user_id=$1`,[lu])).rows.length,0);});
test('storage policy rejects nested and malformed paths',async()=>{await rejects(ana,"insert into storage.objects(bucket_id,name) values('private-memories',$1)",[`${a}/${ana}/${pregnancyA}/nested/file.png`]);for(const path of ['', 'invalid/a/b/c','../../a/b'])assert.equal((await as(ana,tx=>tx.query('select private.owns_storage_path($1) as allowed',[path]))).rows[0].allowed,false);});

test('all memory categories support private CRUD and preserve ownership',async()=>{
 for(const category of ['diary','memory','milestone','photo','ultrasound','letter','moment']) {
  const inserted=await as(ana,tx=>tx.query('insert into public.private_memories(clinic_id,user_id,pregnancy_id,category,body,occurred_on,gestational_week) values($1,$2,$3,$4,$5,$6,$7) returning id,occurred_on,gestational_week',[a,ana,pregnancyA,category,'Texto privado','2026-09-18',20]));
  const id=inserted.rows[0].id;
  assert.equal(inserted.rows[0].gestational_week,20);
  for(const uid of [bia,admin,staff,otherAdmin,superadmin]){
   assert.equal((await as(uid,tx=>tx.query('select body from public.private_memories where id=$1',[id]))).rows.length,0);
   assert.equal((await as(uid,tx=>tx.query("update public.private_memories set body='intrusion' where id=$1 returning id",[id]))).rows.length,0);
   assert.equal((await as(uid,tx=>tx.query('delete from public.private_memories where id=$1 returning id',[id]))).rows.length,0);
  }
  assert.equal((await as(ana,tx=>tx.query('select body from public.private_memories where id=$1',[id]))).rows[0].body,'Texto privado');
  assert.equal((await as(ana,tx=>tx.query("update public.private_memories set body='Revisto' where id=$1 returning body",[id]))).rows[0].body,'Revisto');
  assert.equal((await as(ana,tx=>tx.query('delete from public.private_memories where id=$1 returning id',[id]))).rows.length,1);
 }
 await rejects(ana,'insert into public.private_memories(clinic_id,user_id,pregnancy_id,category,gestational_week) values($1,$2,$3,$4,$5)',[a,ana,pregnancyA,'milestone',43]);
 await rejects(ana,'insert into public.private_memories(clinic_id,user_id,pregnancy_id,category) values($1,$2,$3,$4)',[a,ana,pregnancyA,'unsupported']);
});

let directUser:string,directPregnancy:string,partnerUser:string,partnerCode:string;
test('individual registration creates a real clinic-free journey, consent and unpaid subscription',async()=>{
 directUser=randomUUID();const due=new Date(Date.now()+140*86400000).toISOString().slice(0,10);
 await db.query('insert into auth.users(id,raw_user_meta_data) values($1,$2)',[directUser,JSON.stringify({full_name:'Teste individual',entry_mode:'direct',plan_code:'monthly',due_date:due,terms_version:'2026-09-06',privacy_version:'2026-09-06',sensitive_consent:true})]);
 const p=(await as(directUser,tx=>tx.query('select * from public.pregnancies'))).rows;assert.equal(p.length,1);assert.equal(p[0].clinic_id,null);directPregnancy=p[0].id;
 assert.equal((await as(directUser,tx=>tx.query('select * from public.clinic_memberships'))).rows.length,0);
 assert.equal((await as(directUser,tx=>tx.query('select * from public.consent_records'))).rows.length,3);
 const s=(await as(directUser,tx=>tx.query('select * from public.subscriptions'))).rows;assert.equal(s[0].status,'past_due');assert.equal(s[0].sponsor_id,null);
});
test('individual registration rejects invalid plans atomically',async()=>{const id=randomUUID();await assert.rejects(()=>db.query('insert into auth.users(id,raw_user_meta_data) values($1,$2)',[id,JSON.stringify({full_name:'Inválida',entry_mode:'direct',plan_code:'missing',due_date:new Date(Date.now()+140*86400000).toISOString().slice(0,10),terms_version:'2026-09-06',privacy_version:'2026-09-06',sensitive_consent:true})]));assert.equal((await db.query('select id from auth.users where id=$1',[id])).rows.length,0);});
test('unpaid individual cannot create private content or self-activate a subscription',async()=>{await rejects(directUser,"insert into private_memories(user_id,pregnancy_id,category) values($1,$2,'diary')",[directUser,directPregnancy]);await rejects(directUser,"update subscriptions set status='active'");await rejects(directUser,"select public.set_access($1,'active')",[directUser]);});
test('manual activation is superadmin-only and produces history',async()=>{await as(superadmin,tx=>tx.query("select public.set_access($1,'active')",[directUser]));const e=(await as(directUser,tx=>tx.query('select * from subscription_events'))).rows;assert.equal(e.length,2);assert.equal(e[1].status,'active');await rejects(admin,"select public.set_access($1,'active')",[directUser]);});
test('individual private content rejects forged nullable tenant ownership',async()=>{await as(directUser,tx=>tx.query("insert into private_memories(user_id,pregnancy_id,category,body) values($1,$2,'diary','Só minha')",[directUser,directPregnancy]));await rejects(directUser,"insert into private_memories(user_id,pregnancy_id,category) values($1,$2,'diary')",[directUser,pregnancyA]);for(const u of [ana,bia,admin,staff,superadmin])assert.equal((await as(u,tx=>tx.query('select * from private_memories where pregnancy_id=$1',[directPregnancy]))).rows.length,0);});
test('individual storage uses owner and pregnancy, never a dummy clinic',async()=>{const path=`personal/${directUser}/${directPregnancy}/test.png`;await as(directUser,tx=>tx.query("insert into storage.objects(bucket_id,name) values('private-memories',$1)",[path]));for(const u of [ana,admin,superadmin])assert.equal((await as(u,tx=>tx.query('select * from storage.objects where name=$1',[path]))).rows.length,0);await rejects(ana,"insert into storage.objects(bucket_id,name) values('private-memories',$1)",[path+'x']);await as(directUser,tx=>tx.query('delete from storage.objects where name=$1',[path]));});
test('partner codes are tenant-scoped and private to administrators',async()=>{partnerCode=(await as(admin,tx=>tx.query("insert into partner_codes(clinic_id,code,label,max_uses) values($1,'TESTACCESS01','Campanha de teste',1) returning id",[a]))).rows[0].id;for(const u of [ana,bia,staff,otherAdmin])assert.equal((await as(u,tx=>tx.query('select * from partner_codes where id=$1',[partnerCode]))).rows.length,0);await rejects(otherAdmin,"insert into partner_codes(clinic_id,code,label) values($1,'ILLEGALCODE','Inválido')",[a]);});
test('public code resolver returns identity only',async()=>{const r=(await as(null,tx=>tx.query("select public.resolve_partner('TESTACCESS01') as value"),'anon')).rows[0].value;assert.deepEqual(Object.keys(r).sort(),['name','slug']);assert.equal(r.slug,'vida-plena');});
test('partner signup associates sponsor atomically and consumes one use',async()=>{partnerUser=randomUUID();await db.query('insert into auth.users(id,raw_user_meta_data) values($1,$2)',[partnerUser,JSON.stringify({full_name:'Parceira',entry_mode:'partner',partner_code:'TESTACCESS01',due_date:new Date(Date.now()+140*86400000).toISOString().slice(0,10),terms_version:'2026-09-06',privacy_version:'2026-09-06',sensitive_consent:true})]);const s=(await as(partnerUser,tx=>tx.query('select * from subscriptions'))).rows[0];assert.equal(s.status,'sponsored');assert.equal(s.sponsor_id,a);assert.equal((await db.query<{uses:number}>('select uses from partner_codes where id=$1',[partnerCode])).rows[0].uses,1);assert.equal((await as(partnerUser,tx=>tx.query('select * from pregnancies'))).rows[0].clinic_id,a);});
test('partner redemption is idempotent and capacity cannot be bypassed',async()=>{await as(partnerUser,tx=>tx.query("select public.redeem_partner('TESTACCESS01')"));assert.equal((await db.query<{uses:number}>('select uses from partner_codes where id=$1',[partnerCode])).rows[0].uses,1);await rejects(bia,"select public.redeem_partner('TESTACCESS01')");await rejects(admin,'update partner_codes set uses=0 where id=$1',[partnerCode]);});
test('expired and inactive codes cannot be redeemed',async()=>{await as(admin,tx=>tx.query("insert into partner_codes(clinic_id,code,label,starts_at,expires_at) values($1,'EXPIREDCODE','Vencido',now()-interval '2 days',now()-interval '1 day')",[a]));await rejects(bia,"select public.redeem_partner('EXPIREDCODE')");await as(admin,tx=>tx.query('update partner_codes set active=false where id=$1',[partnerCode]));await rejects(partnerUser,"select public.redeem_partner('TESTACCESS01')");});
test('platform feature switch overrides enabled clinic setting',async()=>{await as(admin,tx=>tx.query("insert into clinic_feature_flags values($1,'community',true)",[a]));assert.equal((await as(ana,tx=>tx.query("select public.feature_enabled('community',$1) as value",[a]))).rows[0].value,false);await as(superadmin,tx=>tx.query("update feature_flags set enabled=true where key='community'"));assert.equal((await as(ana,tx=>tx.query("select public.feature_enabled('community',$1) as value",[a]))).rows[0].value,true);await as(admin,tx=>tx.query("update clinic_feature_flags set enabled=false where clinic_id=$1 and key='community'",[a]));assert.equal((await as(ana,tx=>tx.query("select public.feature_enabled('community',$1) as value",[a]))).rows[0].value,false);});
test('patients and clinic staff cannot enable feature flags',async()=>{for(const u of [ana,staff,otherAdmin])assert.equal((await as(u,tx=>tx.query("update clinic_feature_flags set enabled=true where clinic_id=$1 returning *",[a]))).rows.length,0);assert.equal((await as(admin,tx=>tx.query('update feature_flags set enabled=true returning *'))).rows.length,0);});
test('professionals follow tenant permissions and are editable by admins only',async()=>{const id=(await as(admin,tx=>tx.query("insert into clinic_professionals(clinic_id,name,specialty) values($1,'Profissional fictícia','Especialidade de teste') returning id",[a]))).rows[0].id;assert.equal((await as(ana,tx=>tx.query('select * from clinic_professionals where id=$1',[id]))).rows.length,1);assert.equal((await as(otherAdmin,tx=>tx.query('select * from clinic_professionals where id=$1',[id]))).rows.length,0);assert.equal((await as(staff,tx=>tx.query("update clinic_professionals set name='Intrusão' where id=$1 returning *",[id]))).rows.length,0);await as(admin,tx=>tx.query('delete from clinic_professionals where id=$1',[id]));});
test('campaigns cannot reference another clinic service',async()=>{const svc=(await db.query<{id:string}>("insert into clinic_services(clinic_id,name) values($1,'Serviço externo') returning id",[b])).rows[0].id;await rejects(admin,"insert into clinic_campaigns(clinic_id,service_id,title,body,starts_on,ends_on,week_from,week_to,cta) values($1,$2,'Título','Texto',current_date,current_date+1,1,40,'https://example.com')",[a,svc]);});
test('global metrics expose aggregates only and reject clinic or patient',async()=>{for(const u of [admin,ana,staff])await rejects(u,'select public.platform_metrics()');const m=(await as(superadmin,tx=>tx.query('select public.platform_metrics() as value'))).rows[0].value;assert.ok(m.users>0);assert.ok(Object.values(m).every(v=>typeof v==='number'));});
test('clinic bootstrap is atomic and only superadmin may create it',async()=>{await rejects(admin,"select public.create_clinic('Clínica','new-clinic','{}')");await rejects(superadmin,"select public.create_clinic('Clínica','new-clinic','{}')");assert.equal((await db.query("select * from clinics where slug='new-clinic'")).rows.length,0);});
test('individual account cascade removes subscriptions and history without orphans',async()=>{await db.query('delete from auth.users where id=$1',[directUser]);for(const t of ['profiles','pregnancies','consent_records','private_memories','subscriptions','subscription_events'])assert.equal((await db.query(`select * from ${t} where user_id=$1`,[directUser])).rows.length,0);});

let inviteId:string,sharedId:string,communityId:string,categoryId:string;
const inviteHash='a'.repeat(64);
test('companion module denies creating invitations when disabled',async()=>{await rejects(ana,"insert into companion_invites(pregnancy_id,user_id,email,token_hash) values($1,$2,'companion@example.test',$3)",[pregnancyA,ana,inviteHash]);});
test('companion invitation accepts only the intended account',async()=>{await db.exec("update feature_flags set enabled=true where key in('companion','book','postpartum','community','radar','referrals');update clinic_feature_flags set enabled=true where key='community'");await db.query("update auth.users set email='companion@example.test' where id=$1",[bia]);inviteId=(await as(ana,tx=>tx.query("insert into companion_invites(pregnancy_id,user_id,email,token_hash) values($1,$2,'companion@example.test',$3) returning id",[pregnancyA,ana,inviteHash]))).rows[0].id;await rejects(staff,'select public.accept_companion($1)',[inviteHash]);await rejects(ana,'select public.accept_companion($1)',[inviteHash]);await as(bia,tx=>tx.query('select public.accept_companion($1)',[inviteHash]));await rejects(bia,'select public.accept_companion($1)',[inviteHash]);});
test('one companion per journey and no fabricated acceptance',async()=>{await rejects(ana,"insert into companion_invites(pregnancy_id,user_id,email,token_hash) values($1,$2,'other@example.test',$3)",[pregnancyA,ana,'b'.repeat(64)]);await rejects(ana,"update companion_invites set companion_id=$1 where id=$2",[staff,inviteId]);});
test('companion overview never exposes pregnancy records or unshared memories',async()=>{const view=(await as(bia,tx=>tx.query('select public.companion_overview() as value'))).rows[0].value;assert.equal(view.length,1);assert.deepEqual(Object.keys(view[0]).sort(),['clinic_slug','due_date','id','mother_name','status']);assert.equal((await as(bia,tx=>tx.query('select * from pregnancies where id=$1',[pregnancyA]))).rows.length,0);assert.equal((await as(bia,tx=>tx.query('select * from private_memories where pregnancy_id=$1',[pregnancyA]))).rows.length,0);});
test('explicit shared content and file are read-only for the accepted companion',async()=>{sharedId=(await as(ana,tx=>tx.query("insert into private_memories(clinic_id,user_id,pregnancy_id,category,body,storage_path) values($1,$2,$3,'photo','Registro compartilhado',$4) returning id",[a,ana,pregnancyA,`${a}/${ana}/${pregnancyA}/shared.png`]))).rows[0].id;await as(ana,tx=>tx.query("insert into storage.objects(bucket_id,name) values('private-memories',$1)",[`${a}/${ana}/${pregnancyA}/shared.png`]));assert.equal((await as(bia,tx=>tx.query('select public.shared_memory($1) as value',[sharedId]))).rows[0].value,null);await as(ana,tx=>tx.query('insert into memory_shares(memory_id,invitation_id,user_id) values($1,$2,$3)',[sharedId,inviteId,ana]));assert.equal((await as(bia,tx=>tx.query('select public.shared_memory($1) as value',[sharedId]))).rows[0].value.body,'Registro compartilhado');assert.equal((await as(bia,tx=>tx.query('select * from storage.objects where name=$1',[`${a}/${ana}/${pregnancyA}/shared.png`]))).rows.length,1);assert.equal((await as(bia,tx=>tx.query("update private_memories set body='modificado' where id=$1 returning id",[sharedId]))).rows.length,0);for(const u of [staff,admin,superadmin])assert.equal((await as(u,tx=>tx.query('select public.shared_memory($1) as value',[sharedId]))).rows[0].value,null);});
test('time capsule blocks companion access before its date, not owner access',async()=>{await as(ana,tx=>tx.query('insert into time_capsules(memory_id,user_id,opens_on) values($1,$2,current_date+5)',[sharedId,ana]));assert.equal((await as(bia,tx=>tx.query('select public.shared_memory($1) as value',[sharedId]))).rows[0].value,null);assert.equal((await as(bia,tx=>tx.query('select * from storage.objects where name=$1',[`${a}/${ana}/${pregnancyA}/shared.png`]))).rows.length,0);assert.equal((await as(ana,tx=>tx.query('select * from private_memories where id=$1',[sharedId]))).rows.length,1);await as(ana,tx=>tx.query('update time_capsules set opens_on=current_date where memory_id=$1',[sharedId]));assert.ok((await as(bia,tx=>tx.query('select public.shared_memory($1) as value',[sharedId]))).rows[0].value);});
test('capsule cancellation preserves memory and rejects another owner',async()=>{assert.equal((await as(bia,tx=>tx.query('delete from time_capsules where memory_id=$1 returning *',[sharedId]))).rows.length,0);await as(ana,tx=>tx.query('delete from time_capsules where memory_id=$1',[sharedId]));assert.equal((await as(ana,tx=>tx.query('select * from private_memories where id=$1',[sharedId]))).rows.length,1);});
test('revoking companion immediately revokes shared files and content',async()=>{await as(ana,tx=>tx.query("update companion_invites set status='revoked' where id=$1",[inviteId]));assert.equal((await as(bia,tx=>tx.query('select public.shared_memory($1) as value',[sharedId]))).rows[0].value,null);assert.deepEqual((await as(bia,tx=>tx.query('select public.companion_overview() as value'))).rows[0].value,[]);assert.equal((await as(bia,tx=>tx.query('select * from storage.objects where name=$1',[`${a}/${ana}/${pregnancyA}/shared.png`]))).rows.length,0);await as(ana,tx=>tx.query('delete from storage.objects where name=$1',[`${a}/${ana}/${pregnancyA}/shared.png`]));});
test('birth changes journey stage atomically and remains private',async()=>{await as(ana,tx=>tx.query("insert into birth_records(pregnancy_id,user_id,born_at,name) values($1,$2,now()-interval '1 day','Bebê fictício')",[pregnancyA,ana]));assert.equal((await as(ana,tx=>tx.query('select status from pregnancies where id=$1',[pregnancyA]))).rows[0].status,'completed');for(const u of [bia,staff,admin,superadmin])assert.equal((await as(u,tx=>tx.query('select * from birth_records where pregnancy_id=$1',[pregnancyA]))).rows.length,0);await rejects(ana,'update birth_records set born_at=now()+interval \'1 day\' where pregnancy_id=$1',[pregnancyA]);});
test('removing a mistaken birth record restores gestation without deleting memories',async()=>{await as(ana,tx=>tx.query('delete from birth_records where pregnancy_id=$1',[pregnancyA]));assert.equal((await as(ana,tx=>tx.query('select status from pregnancies where id=$1',[pregnancyA]))).rows[0].status,'active');assert.equal((await as(ana,tx=>tx.query('select * from private_memories where id=$1',[sharedId]))).rows.length,1);});
test('book creation is atomic, ordered and owner-scoped',async()=>{const id=(await as(ana,tx=>tx.query("select public.save_journey_book('Minha história',$1) as id",[[sharedId]]))).rows[0].id;assert.equal((await as(ana,tx=>tx.query('select * from journey_book_items where book_id=$1',[id]))).rows[0].position,1);for(const u of [bia,admin,superadmin])assert.equal((await as(u,tx=>tx.query('select * from journey_books where id=$1',[id]))).rows.length,0);await rejects(bia,"select public.save_journey_book('Roubo',$1)",[[sharedId]]);await rejects(ana,"select public.save_journey_book('Duplicado',$1)",[[sharedId,sharedId]]);await as(ana,tx=>tx.query('delete from journey_books where id=$1',[id]));assert.equal((await db.query('select * from journey_book_items where book_id=$1',[id])).rows.length,0);});
test('feature flag disables book creation even through direct RPC',async()=>{await db.exec("update feature_flags set enabled=false where key='book'");await rejects(ana,"select public.save_journey_book('Desativado',$1)",[[sharedId]]);await db.exec("update feature_flags set enabled=true where key='book'");});
test('all editorial periods exist without fabricated medical content',async()=>{assert.equal((await db.query("select * from editorial_content where kind='week'")).rows.length,40);assert.equal((await db.query("select * from editorial_content where kind='postpartum'")).rows.length,91);assert.equal((await as(ana,tx=>tx.query('select * from editorial_content'))).rows.length,0);});
test('editorial publication requires an approved reviewer and source',async()=>{await rejects(superadmin,"update editorial_content set status='published' where week=1");assert.equal((await as(admin,tx=>tx.query("update editorial_content set title='Proibido' returning *"))).rows.length,0);await as(superadmin,tx=>tx.query("update editorial_content set title='Leitura sintética de teste',body='Acolhimento editorial',review_status='approved',reviewer='Revisor de teste',reviewed_at=now(),source_url='https://example.com',status='published',published_at=now() where kind='week' and week=1"));assert.equal((await as(ana,tx=>tx.query("select * from editorial_content where week=1"))).rows.length,1);});
test('private search includes owner text and approved editorial, never another mother',async()=>{const rows=(await as(ana,tx=>tx.query("select * from public.search_journey('compartilhado')"))).rows;assert.ok(rows.some(r=>r.id===sharedId));assert.equal((await as(bia,tx=>tx.query("select * from public.search_journey('compartilhado')"))).rows.length,0);assert.ok((await as(ana,tx=>tx.query("select * from public.search_journey('acolhimento')"))).rows.length);assert.equal((await as(ana,tx=>tx.query("select * from public.search_journey('compartilhado','letter')"))).rows.length,0);});
test('community accepts patients, not clinic operations or companion-only users',async()=>{for(const u of [admin,staff,otherAdmin])assert.equal((await as(u,tx=>tx.query('select public.community_access() as allowed'))).rows[0].allowed,false);assert.equal((await as(ana,tx=>tx.query('select public.community_access() as allowed'))).rows[0].allowed,true);categoryId=(await as(ana,tx=>tx.query('select id from community_categories limit 1'))).rows[0].id;});
test('community publication has real persistence and rejects forged authors',async()=>{communityId=(await as(ana,tx=>tx.query("insert into community_posts(user_id,category_id,alias,title,body) values($1,$2,'Ana teste','Conversa de teste','Texto de teste') returning id",[ana,categoryId]))).rows[0].id;assert.equal((await as(bia,tx=>tx.query('select * from community_posts where id=$1',[communityId]))).rows.length,1);await rejects(bia,"insert into community_posts(user_id,category_id,alias,title,body) values($1,$2,'Falso','Título','Texto')",[ana,categoryId]);assert.equal((await as(bia,tx=>tx.query("update community_posts set body='Roubo' where id=$1 returning id",[communityId]))).rows.length,0);await rejects(ana,"update community_posts set status='hidden' where id=$1",[communityId]);});
test('moderation hides and restores content with immutable decision history',async()=>{await rejects(admin,"select public.moderate('community_posts',$1,'hidden','Teste')",[communityId]);await as(superadmin,tx=>tx.query("select public.moderate('community_posts',$1,'hidden','Revisar relato')",[communityId]));assert.equal((await as(bia,tx=>tx.query('select * from community_posts where id=$1',[communityId]))).rows.length,0);await as(superadmin,tx=>tx.query("select public.moderate('community_posts',$1,'published','Revisão concluída')",[communityId]));assert.equal((await as(bia,tx=>tx.query('select * from community_posts where id=$1',[communityId]))).rows.length,1);assert.equal((await as(superadmin,tx=>tx.query('select * from moderation_logs where entity_id=$1',[communityId]))).rows.length,2);await rejects(ana,'delete from moderation_logs');});
test('community reporting is private and cannot be closed by its author',async()=>{const id=(await as(bia,tx=>tx.query("insert into community_reports(user_id,post_id,reason) values($1,$2,'medical_risk') returning id",[bia,communityId]))).rows[0].id;assert.equal((await as(ana,tx=>tx.query('select * from community_reports where id=$1',[id]))).rows.length,0);await rejects(bia,"update community_reports set status='resolved'");await as(superadmin,tx=>tx.query("select public.moderate('community_reports',$1,'resolved','Análise concluída')",[id]));});
test('community blocking revokes reading and posting immediately',async()=>{await as(superadmin,tx=>tx.query("select public.moderate('community_bans',$1,'block','Abuso de teste')",[bia]));assert.equal((await as(bia,tx=>tx.query('select * from community_posts'))).rows.length,0);await rejects(bia,"insert into community_posts(user_id,category_id,alias,title,body) values($1,$2,'Bia','Título','Texto')",[bia,categoryId]);await as(superadmin,tx=>tx.query("select public.moderate('community_bans',$1,'restore','Restaurado')",[bia]));});
test('community rate limit cannot be bypassed by backdating posts',async()=>{for(let i=0;i<9;i++)await as(ana,tx=>tx.query("insert into community_posts(user_id,category_id,alias,title,body,created_at) values($1,$2,'Ana','Título de teste','Teste','2000-01-01')",[ana,categoryId]));await rejects(ana,"insert into community_posts(user_id,category_id,alias,title,body) values($1,$2,'Ana','Limite','Teste')",[ana,categoryId]);});
test('communication preferences are audited and never default to opt-in',async()=>{assert.equal((await as(ana,tx=>tx.query('select * from communication_preferences'))).rows.length,0);await as(ana,tx=>tx.query('insert into communication_preferences(user_id,weekly_email) values($1,true)',[ana]));await as(ana,tx=>tx.query('update communication_preferences set weekly_email=false where user_id=$1',[ana]));assert.equal((await as(ana,tx=>tx.query('select * from communication_consent_history'))).rows.length,2);assert.equal((await as(admin,tx=>tx.query('select * from communication_preferences'))).rows.length,0);await rejects(ana,'select public.schedule_weekly()');await rejects(ana,'select public.claim_emails()');});
test('referral codes cannot be registered in another account name',async()=>{await rejects(ana,'insert into referral_codes(user_id,code) values($1,$2)',[bia,'a'.repeat(24)]);await as(ana,tx=>tx.query('insert into referral_codes(user_id,code) values($1,$2)',[ana,'a'.repeat(24)]));assert.equal((await as(bia,tx=>tx.query('select * from referral_codes'))).rows.length,0);});
test('null reviewer cannot bypass editorial publication constraint',async()=>{await rejects(superadmin,"update editorial_content set review_status='approved',reviewer=null,reviewed_at=now(),source_url='https://example.com',status='published' where kind='week' and week=2");await rejects(superadmin,"update editorial_content set review_status='approved',reviewer='  ',reviewed_at=now(),source_url='https://example.com',status='published' where kind='week' and week=2");});
test('scoped search cannot produce links to another journey space',async()=>{assert.equal((await as(ana,tx=>tx.query("select * from search_journey('compartilhado',null,null,null,null,true)"))).rows.length,0);assert.ok((await as(ana,tx=>tx.query("select * from search_journey('compartilhado',null,null,null,$1,true)",[a]))).rows.some(r=>r.id===sharedId));});
test('postpartum memory never advances gestational week',async()=>{await as(ana,tx=>tx.query("insert into birth_records(pregnancy_id,user_id,born_at) values($1,$2,now()-interval '2 days')",[pregnancyA,ana]));const r=await as(ana,tx=>tx.query("insert into private_memories(clinic_id,user_id,pregnancy_id,category,body,occurred_on,gestational_week) values($1,$2,$3,'memory','Depois da chegada',current_date,42) returning id,gestational_week",[a,ana,pregnancyA]));assert.equal(r.rows[0].gestational_week,null);await as(ana,tx=>tx.query('delete from private_memories where id=$1',[r.rows[0].id]));await as(ana,tx=>tx.query('delete from birth_records where pregnancy_id=$1',[pregnancyA]));});
test('capsule edits update only allowed fields and retain original ownership',async()=>{await as(ana,tx=>tx.query('insert into time_capsules(memory_id,user_id) values($1,$2)',[sharedId,ana]));await as(ana,tx=>tx.query("update time_capsules set recipient='Meu bebê',opens_on=current_date+10 where memory_id=$1",[sharedId]));await rejects(ana,'update time_capsules set user_id=$1 where memory_id=$2',[bia,sharedId]);assert.equal((await as(ana,tx=>tx.query('select recipient from time_capsules where memory_id=$1',[sharedId]))).rows[0].recipient,'Meu bebê');await as(ana,tx=>tx.query('delete from time_capsules where memory_id=$1',[sharedId]));});
test('repeated care reaction is idempotent with insert-on-conflict, not privileged update',async()=>{for(let i=0;i<2;i++)await as(bia,tx=>tx.query('insert into community_reactions(post_id,user_id) values($1,$2) on conflict(post_id,user_id) do nothing',[communityId,bia]));assert.equal((await as(bia,tx=>tx.query('select * from community_reactions where post_id=$1',[communityId]))).rows.length,1);});
test('book selection supports atomic edits and optional private birth',async()=>{await as(ana,tx=>tx.query("insert into birth_records(pregnancy_id,user_id,born_at) values($1,$2,now()-interval '1 day')",[pregnancyA,ana]));const id=(await as(ana,tx=>tx.query("select save_book_selection(null,'Nascimento',$1,$2) as id",[[],pregnancyA]))).rows[0].id;await as(ana,tx=>tx.query("select save_book_selection($1,'Livro revisto',$2,null)",[id,[sharedId]]));assert.equal((await as(ana,tx=>tx.query('select title,birth_pregnancy_id from journey_books where id=$1',[id]))).rows[0].title,'Livro revisto');await rejects(bia,"select save_book_selection($1,'Intrusão',$2,null)",[id,[sharedId]]);await rejects(bia,"select save_book_selection(null,'Nascimento de outra pessoa',$1,$2)",[[],pregnancyA]);await rejects(ana,"select save_book_selection($1,'Vazio',null,null)",[id]);assert.equal((await as(ana,tx=>tx.query('select * from journey_book_items where book_id=$1',[id]))).rows.length,1);await as(ana,tx=>tx.query('delete from journey_books where id=$1',[id]));await as(ana,tx=>tx.query('delete from birth_records where pregnancy_id=$1',[pregnancyA]));});
test('cancelling sponsored access blocks new content but preserves private reading and deletion',async()=>{const p=(await as(partnerUser,tx=>tx.query('select id from pregnancies'))).rows[0].id;const m=(await as(partnerUser,tx=>tx.query("insert into private_memories(clinic_id,user_id,pregnancy_id,category,body) values($1,$2,$3,'diary','Antes do cancelamento') returning id",[a,partnerUser,p]))).rows[0].id;await as(partnerUser,tx=>tx.query('select cancel_my_access()'));assert.equal((await as(partnerUser,tx=>tx.query('select status from subscriptions'))).rows[0].status,'cancelled');await rejects(partnerUser,"insert into private_memories(clinic_id,user_id,pregnancy_id,category) values($1,$2,$3,'diary')",[a,partnerUser,p]);await rejects(partnerUser,"insert into storage.objects(bucket_id,name) values('private-memories',$1)",[`${a}/${partnerUser}/${p}/after.png`]);assert.equal((await as(partnerUser,tx=>tx.query('select * from private_memories where id=$1',[m]))).rows.length,1);await as(partnerUser,tx=>tx.query('delete from private_memories where id=$1',[m]));});
