import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PDFDocument} from 'pdf-lib';
import sharp from 'sharp';
import QRCode from 'qrcode';
import {effectiveStatus,paymentProvider} from '../src/lib/subscriptions';
import {postpartumAge} from '../src/lib/postpartum';
import {weeklyEmail} from '../src/lib/email-templates';
import {buildJourneyPdf,pdfText} from '../src/lib/journey-pdf';
import {adminValues} from '../src/lib/admin-catalog';
import {transactionalEmail,shouldScheduleWeekly} from '../src/lib/email-jobs';
test('transactional e-mails do not require weekly opt-in or a pregnancy',()=>{assert.match(transactionalEmail('welcome','https://example.com')!.text,/\/acesso/);assert.match(transactionalEmail('security','https://example.com')!.text,/\/auth\/recuperar/);assert.equal(transactionalEmail('weekly','https://example.com'),null);assert.throws(()=>transactionalEmail('unknown','https://example.com'));});
test('weekly scheduling follows Sunday in Brazil',()=>{assert.equal(shouldScheduleWeekly(new Date('2026-09-20T12:00:00Z')),true);assert.equal(shouldScheduleWeekly(new Date('2026-09-21T12:00:00Z')),false);assert.equal(shouldScheduleWeekly(new Date('2026-09-20T01:00:00Z')),false);});
test('subscription end dates determine effective expiry without claiming payment',()=>{assert.equal(effectiveStatus({status:'trial',ends_at:'2026-01-01'},new Date('2026-02-01')),'expired');assert.equal(effectiveStatus({status:'sponsored',ends_at:null}),'sponsored');assert.equal(effectiveStatus({status:'cancelled',ends_at:'2027-01-01'}),'cancelled');assert.equal(paymentProvider(),null);});
test('postpartum day and week count stop the pregnancy clock',()=>{assert.deepEqual(postpartumAge('2026-01-01T12:00:00Z',new Date('2026-01-08T12:00:00Z')),{days:7,week:2,withinProgram:true});assert.equal(postpartumAge('2026-01-01',new Date('2026-05-01'))?.withinProgram,false);assert.equal(postpartumAge('invalid'),null);});
test('weekly summary contains only approved provided content and opt-out link',()=>{const r=weeklyEmail({week:20,url:'https://example.com/semana/20',preferencesUrl:'https://example.com/preferencias'});assert.ok(r.text.includes('preferencias'));assert.ok(r.subject.includes('20'));assert.ok(!r.text.includes('undefined'));});
test('book creates a valid paginated PDF with Portuguese and long text',async()=>{const bytes=await buildJourneyPdf('Minha gestação',[{title:'Carta para o bebê',text:'Olá, coração. '.repeat(1000)}]);const document=await PDFDocument.load(bytes);assert.ok(document.getPageCount()>2);assert.equal(document.getTitle(),'Minha gestação');assert.ok(pdfText('Olá ❤️').startsWith('Olá'));});
test('book preserves original ultrasound PDF pages',async()=>{const exam=await PDFDocument.create();exam.addPage();exam.addPage();const bytes=await buildJourneyPdf('Meu livro',[{title:'Ultrassom',text:'Observação pessoal',file:{bytes:await exam.save(),type:'application/pdf'}}]);const d=await PDFDocument.load(bytes);assert.equal(d.getPageCount(),4);});
test('QR generation uses local implementation and encodes partner URL',async()=>{const r=await QRCode.toString('https://example.com/parceiro?codigo=ABCDEF1234',{type:'svg'});assert.ok(r.includes('<svg'));assert.ok(r.includes('<path'));});
test('book supports private WebP photos without external conversion',async()=>{const photo=await sharp({create:{width:2,height:2,channels:3,background:'#ffffff'}}).webp().toBuffer();const bytes=await buildJourneyPdf('Minha foto',[{title:'Foto',text:'Legenda',file:{type:'image/webp',bytes:photo}}]);assert.equal((await PDFDocument.load(bytes)).getPageCount(),2);});
test('admin validation strips privilege fields and rejects untrusted URLs',()=>{const f=new FormData();f.set('name','Consulta');f.set('booking_url','javascript:alert(1)');f.set('active','on');assert.equal(adminValues('services',f).success,false);f.set('booking_url','https://example.com');f.set('clinic_id','forged');const r=adminValues('services',f);assert.ok(r.success);assert.ok(!('clinic_id' in r.data));});
