import {requireFeature} from '@/lib/features';
import {buildJourneyPdf,BookEntry} from '@/lib/journey-pdf';
import {recordLabel} from '@/lib/journey-records';
import {ownedMemoryPath} from '@/lib/memories';
import {z} from 'zod';
export async function GET(_:Request,{params}:{params:Promise<{clinic:string;id:string}>}){
 const {clinic:slug,id}=await params;const {db,user}=await requireFeature(slug,'book');if(!z.uuid().safeParse(id).success)return new Response(null,{status:404});
 const book=await db.from('journey_books').select('title,birth_pregnancy_id').eq('id',id).eq('user_id',user.id).maybeSingle();if(book.error||!book.data)return new Response(null,{status:404});
 const items=await db.from('journey_book_items').select('memory_id,position').eq('book_id',id).order('position');if(items.error)return new Response('Não foi possível carregar a seleção.',{status:500});
 try{const entries:BookEntry[]=[];for(const item of items.data){const r=await db.from('private_memories').select('*').eq('id',item.memory_id).eq('user_id',user.id).single();if(r.error)throw new Error('Um registro não está disponível. Crie uma nova seleção.');const m=r.data;const flag=await db.rpc('feature_enabled',{p_key:'book',p_clinic:m.clinic_id});if(flag.error||!flag.data)return new Response(null,{status:404});const entry:BookEntry={title:`${recordLabel(m.category)} · ${m.occurred_on}`,text:m.body??''};if(m.storage_path){if(!ownedMemoryPath(m.storage_path,m.clinic_id,user.id,m.pregnancy_id))throw new Error('Não foi possível conferir um arquivo.');const f=await db.storage.from('private-memories').download(m.storage_path);if(f.error)throw new Error('Um arquivo não está disponível. Tente novamente.');entry.file={bytes:new Uint8Array(await f.data.arrayBuffer()),type:f.data.type};}entries.push(entry);}if(book.data.birth_pregnancy_id){const b=await db.from('birth_records').select('born_at,name,sex,weight_grams,length_cm,note').eq('pregnancy_id',book.data.birth_pregnancy_id).eq('user_id',user.id).single();if(b.error)throw new Error('O nascimento não está disponível. Revise a seleção.');entries.push({title:'Nascimento',text:[b.data.name,new Date(b.data.born_at).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'}),b.data.weight_grams?`${b.data.weight_grams} g`:null,b.data.length_cm?`${b.data.length_cm} cm`:null,b.data.note].filter(Boolean).join('\n')});}const bytes=await buildJourneyPdf(book.data.title,entries);return new Response(new Uint8Array(bytes),{headers:{'Content-Type':'application/pdf','Content-Disposition':'attachment; filename="livro-da-jornada.pdf"','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}catch(e){return new Response(e instanceof Error?e.message:'Não foi possível gerar o livro.',{status:422,headers:{'Cache-Control':'private, no-store'}});}
}
