'use server';
import {z} from 'zod';
import {revalidatePath} from 'next/cache';
import {requireCommunity} from '@/lib/community';
import {requireSuperadmin} from '@/lib/access';
import type {ManageState} from '@/app/gestao/actions';
export async function post(id:string|null,_:ManageState,form:FormData):Promise<ManageState>{const {db,user}=await requireCommunity();
 if(form.get('operation')==='delete'){if(form.get('confirm')!=='on'||!id)return {error:'Confirme a exclusão.'};const r=await db.from('community_posts').delete().eq('id',id).eq('user_id',user.id).select('id').single();if(r.error)return {error:'Não foi possível excluir.'};}
 else{const p=z.object({alias:z.string().trim().min(2).max(60),title:z.string().trim().min(2).max(160),body:z.string().trim().min(1).max(5000),category_id:z.uuid()}).safeParse(Object.fromEntries(form));if(!p.success)return {error:'Confira apelido, título, categoria e texto.'};const {alias,...content}=p.data;const r=id?await db.from('community_posts').update(content).eq('id',id).eq('user_id',user.id).select('id').single():await db.from('community_posts').insert({...content,alias,user_id:user.id}).select('id').single();if(r.error)return {error:'Não foi possível publicar. Confira os campos e aguarde caso tenha publicado várias vezes.'};}
 revalidatePath('/comunidade','layout');return {success:'Publicação atualizada.'};
}
export async function comment(postId:string,id:string|null,_:ManageState,form:FormData):Promise<ManageState>{const {db,user}=await requireCommunity();let r;
 if(form.get('operation')==='delete'){if(form.get('confirm')!=='on'||!id)return {error:'Confirme a exclusão.'};r=await db.from('community_comments').delete().eq('id',id).eq('user_id',user.id).select('id').single();}
 else{const p=z.object({alias:z.string().trim().min(2).max(60),body:z.string().trim().min(1).max(2000)}).safeParse(Object.fromEntries(form));if(!p.success)return {error:'Confira o apelido e o comentário.'};r=id?await db.from('community_comments').update({body:p.data.body}).eq('id',id).eq('user_id',user.id).select('id').single():await db.from('community_comments').insert({...p.data,user_id:user.id,post_id:postId}).select('id').single();}
 if(r.error)return {error:'Não foi possível salvar. Aguarde se comentou várias vezes recentemente.'};revalidatePath('/comunidade','layout');return {success:'Comentário atualizado.'};
}
export async function react(postId:string,_:ManageState,form:FormData):Promise<ManageState>{const {db,user}=await requireCommunity();const r=form.get('care')==='on'?await db.from('community_reactions').upsert({post_id:postId,user_id:user.id},{onConflict:'post_id,user_id',ignoreDuplicates:true}):await db.from('community_reactions').delete().eq('post_id',postId).eq('user_id',user.id);if(r.error)return {error:'Não foi possível atualizar sua reação.'};revalidatePath('/comunidade','layout');return {success:'Reação atualizada.'};}
export async function report(postId:string|null,commentId:string|null,_:ManageState,form:FormData):Promise<ManageState>{const {db,user}=await requireCommunity();const p=z.object({reason:z.enum(['medical_risk','spam','harassment','privacy','other']),detail:z.string().max(1000)}).safeParse(Object.fromEntries(form));if(!p.success)return {error:'Confira o motivo.'};const r=await db.from('community_reports').insert({...p.data,user_id:user.id,post_id:postId,comment_id:commentId});if(r.error)return {error:'Não foi possível enviar. Tente novamente mais tarde.'};return {success:'Denúncia encaminhada à moderação.'};}
export async function moderate(_:ManageState,form:FormData):Promise<ManageState>{const {db}=await requireSuperadmin();const p=z.object({entity:z.enum(['community_posts','community_comments','community_reports','community_bans']),id:z.uuid(),action:z.enum(['hidden','removed','published','resolved','block','restore']),reason:z.string().trim().min(2).max(1000)}).safeParse(Object.fromEntries(form));if(!p.success)return {error:'Confira a ação e registre o motivo.'};const v=p.data;const r=await db.rpc('moderate',{p_entity:v.entity,p_id:v.id,p_action:v.action,p_reason:v.reason});if(r.error)return {error:'Não foi possível aplicar esta ação.'};revalidatePath('/','layout');return {success:'Ação aplicada e registrada.'};}
