import {before,after,test} from 'node:test';import assert from 'node:assert/strict';import {createClient,type SupabaseClient} from '@supabase/supabase-js';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL!,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,password=process.env.DEMO_PASSWORD!;
const ready=!!(url&&key&&password),skip=ready?false:'Conexão real necessária';
const A='10000000-0000-4000-8000-000000000001',B='20000000-0000-4000-8000-000000000001';
const names=['ana','beatriz','luisa','admin.vida','equipe.vida','admin.horizonte','jatoba'];
const db:Record<string,SupabaseClient>={},uid:Record<string,string>={};
const client=()=>createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false},global:{fetch:(a,b)=>fetch(a,{...b,signal:AbortSignal.timeout(45000)})}});
function ok<T extends {error:unknown}>(r:T):T{assert.ifError(r.error);return r;}
function denied(r:{error:unknown;data:unknown}){assert.ok(r.error||Array.isArray(r.data)&&r.data.length===0);}
before(async()=>{if(!ready)return;await Promise.all(names.map(async n=>{db[n]=client();uid[n]=ok(await db[n].auth.signInWithPassword({email:`${n}@jornada.example.com`,password})).data.user!.id;}));});
after(async()=>{await Promise.all(Object.values(db).map(c=>c.auth.signOut({scope:'local'})));});
test('RLS real: cada gestante só lê seu perfil, gestação, memórias e aceites',{skip},async()=>{await Promise.all(['ana','beatriz','luisa'].map(async n=>{await Promise.all(['profiles','pregnancies','private_memories','consent_records'].map(async table=>{const rows=ok(await db[n].from(table).select('*')).data!;assert.equal(rows.length,table==='consent_records'?3:1);assert.ok(rows.every(r=>r.user_id===uid[n]));}));}));});
test('RLS real: equipe e administradores só leem operações de seu tenant',{skip},async()=>{await Promise.all(['admin.vida','equipe.vida','admin.horizonte'].map(async n=>{const rows=ok(await db[n].from('pregnancies').select('*')).data!,cid=n==='admin.horizonte'?B:A;assert.equal(rows.length,cid===A?2:1);assert.ok(rows.every(r=>r.clinic_id===cid));await Promise.all(['private_memories','consent_records'].map(async table=>assert.equal(ok(await db[n].from(table).select('*')).data!.length,0)));}));});
test('RLS real: superadmin não lê dados privados ou operacionais de gestantes',{skip},async()=>{assert.equal(ok(await db.jatoba.from('clinics').select('*')).data!.length,2);await Promise.all(['pregnancies','private_memories','consent_records'].map(async table=>assert.equal(ok(await db.jatoba.from(table).select('*')).data!.length,0)));});
test('RLS real: alterações de papel, consentimento e auditoria são recusadas',{skip},async()=>{await Promise.all([db.ana.from('clinic_memberships').update({role:'clinic_admin'}).eq('user_id',uid.ana),db.ana.from('superadmins').insert({user_id:uid.ana}),db.ana.from('consent_records').update({version:'forged'}).eq('user_id',uid.ana),db.ana.from('audit_logs').insert({action:'FORGED',entity:'test'})].map(async r=>assert.ok((await r).error)));});
test('RLS real: RPC recusa outra clínica, autopromoção e conversão de gestante',{skip},async()=>{await Promise.all([db['admin.vida'].rpc('set_staff_membership',{p_clinic_id:B,p_user_id:uid['equipe.vida'],p_role:'clinic_admin'}),db['admin.vida'].rpc('set_staff_membership',{p_clinic_id:A,p_user_id:uid.ana,p_role:'clinic_admin'}),db['admin.vida'].rpc('set_staff_membership',{p_clinic_id:A,p_user_id:uid['admin.vida'],p_role:'clinic_staff'}),db['equipe.vida'].rpc('set_staff_membership',{p_clinic_id:A,p_user_id:uid['admin.vida'],p_role:'clinic_staff'})].map(async r=>assert.ok((await r).error)));});
test('RLS real: revogação de vínculo bloqueia sessão existente imediatamente',{skip},async()=>{try{ok(await db['admin.vida'].rpc('set_staff_membership',{p_clinic_id:A,p_user_id:uid['equipe.vida'],p_role:'clinic_staff',p_active:false}));assert.equal(ok(await db['equipe.vida'].from('pregnancies').select('*')).data!.length,0);assert.equal(ok(await db['equipe.vida'].rpc('my_clinic_links')).data.length,0);}finally{ok(await db['admin.vida'].rpc('set_staff_membership',{p_clinic_id:A,p_user_id:uid['equipe.vida'],p_role:'clinic_staff',p_active:true}));}});
test('RLS real: FK composta e propriedade impedem misturar gestação e clínica',{skip},async()=>{const p=ok(await db.luisa.from('pregnancies').select('id').single()).data!;assert.ok((await db.ana.from('private_memories').insert({clinic_id:A,user_id:uid.ana,pregnancy_id:p.id,category:'diary'})).error);const own=ok(await db.ana.from('private_memories').select('id').single()).data!;assert.ok((await db.ana.from('private_memories').update({user_id:uid.beatriz}).eq('id',own.id)).error);denied(await db.beatriz.from('private_memories').delete().eq('id',own.id).select());});
test('Temas reais: atualização persistente da Vida Plena preserva Horizonte',{skip},async()=>{const anon=client();const a=ok(await anon.rpc('get_public_clinic',{p_slug:'vida-plena'})).data,b=ok(await anon.rpc('get_public_clinic',{p_slug:'clinica-horizonte'})).data;assert.notDeepEqual(a.tokens,b.tokens);try{const tokens={...a.tokens,primary:'#654333'};await Promise.all(['ana','equipe.vida','admin.horizonte'].map(async n=>denied(await db[n].from('clinic_themes').update({tokens}).eq('clinic_id',A).select())));ok(await db['admin.vida'].from('clinic_themes').update({tokens}).eq('clinic_id',A).select().single());assert.equal(ok(await anon.rpc('get_public_clinic',{p_slug:'vida-plena'})).data.tokens.primary,'#654333');assert.deepEqual(ok(await anon.rpc('get_public_clinic',{p_slug:'clinica-horizonte'})).data.tokens,b.tokens);assert.ok((await db['admin.vida'].from('clinic_themes').update({tokens:{...tokens,primary:'red;position:absolute'}}).eq('clinic_id',A)).error);}finally{ok(await db['admin.vida'].from('clinic_themes').update({tokens:a.tokens}).eq('clinic_id',A));}});
test('Auth real: renovação de sessão e refresh revogado após logout',{skip},async()=>{const auth=client();ok(await auth.auth.signInWithPassword({email:'ana@jornada.example.com',password}));assert.equal(ok(await auth.auth.getUser()).data.user?.id,uid.ana);const session=ok(await auth.auth.refreshSession()).data.session!;ok(await auth.auth.signOut({scope:'local'}));assert.equal(ok(await auth.auth.getSession()).data.session,null);assert.ok((await auth.auth.refreshSession({refresh_token:session.refresh_token})).error);});
