import {test} from 'node:test';import assert from 'node:assert/strict';import {createClient} from '@supabase/supabase-js';
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,password=process.env.DEMO_PASSWORD;
const ready=Boolean(url&&key&&password);
const skip=ready?false:'Supabase não conectado e/ou contas de demonstração não provisionadas. Não valida Auth com mocks.';
const client=()=>createClient(url!,key!,{auth:{persistSession:false,autoRefreshToken:false}});
async function login(email:string){const db=client();const {data,error}=await db.auth.signInWithPassword({email,password:password!});assert.ifError(error);assert.ok(data.user);return db;}
test('real Supabase Auth: wrong password rejected, verified user and logout', {skip},async()=>{const db=client();assert.ok((await db.auth.signInWithPassword({email:'ana@jornada.example.com',password:'INCORRETA-00000'})).error);const auth=await login('ana@jornada.example.com');assert.ok((await auth.auth.getUser()).data.user);assert.ifError((await auth.auth.signOut({scope:'local'})).error);assert.equal((await auth.auth.getSession()).data.session,null);});
test('real PostgREST RLS: own patient data only', {skip},async()=>{const db=await login('ana@jornada.example.com');try{const {data,error}=await db.from('pregnancies').select('*');assert.ifError(error);assert.equal(data?.length,1);assert.equal(data?.[0].display_name,'Ana Carolina');const bad=await db.from('clinic_memberships').update({role:'clinic_admin'}).eq('user_id',data![0].user_id).select();assert.ok(bad.error||bad.data?.length===0);}finally{await db.auth.signOut({scope:'local'});}});
test('real PostgREST RLS: clinic staff cannot read memories or cross tenants', {skip},async()=>{const db=await login('admin.vida@jornada.example.com');try{const {data,error}=await db.from('pregnancies').select('clinic_id');assert.ifError(error);assert.ok(data?.length);assert.ok(data?.every(p=>p.clinic_id==='10000000-0000-4000-8000-000000000001'));const m=await db.from('private_memories').select('*');assert.ifError(m.error);assert.equal(m.data?.length,0);}finally{await db.auth.signOut({scope:'local'});}});
test('real backend: clinic themes persist independently', {skip},async()=>{const db=client();const a=await db.rpc('get_public_clinic',{p_slug:'vida-plena'}),b=await db.rpc('get_public_clinic',{p_slug:'clinica-horizonte'});assert.ifError(a.error);assert.ifError(b.error);assert.notEqual(a.data.id,b.data.id);assert.notDeepEqual(a.data.tokens,b.data.tokens);});
