 'use client';
import {useState,useActionState,useEffect} from 'react';import {themeKeys,themeStyle,type Theme} from '@/lib/theme';import {saveTheme} from '@/app/[clinic]/clinica/tema/actions';import {Submit} from './submit';
import type {Clinic} from '@/lib/access';
const labels:Record<keyof Theme,string>={primary:'Principal',primarySoft:'Principal suave',secondary:'Secundária',accent:'Apoio',background:'Fundo',surface:'Superfícies',text:'Texto',muted:'Texto secundário',border:'Bordas',onPrimary:'Texto dos botões',danger:'Mensagens de erro',focus:'Foco do teclado'};
export function ThemeEditor({slug,initial,logo,identity}:{slug:string;initial:Theme;logo:string|null;identity?:Clinic}){
 const [tokens,setTokens]=useState(initial);const [state,action]=useActionState(saveTheme.bind(null,slug),{});
 const [logoUrl,setLogoUrl]=useState(logo||'');
 useEffect(()=>setLogoUrl(logo||''),[logo]);
 return <div className="stack"><form action={action} className="form panel"><input type="hidden" name="tokens" value={JSON.stringify(tokens)}/><label>Endereço da logo original<input name="logo_url" type="url" value={logoUrl} onChange={e=>setLogoUrl(e.target.value)} placeholder="https://"/><span className="form-note">Use o arquivo aprovado pela clínica.</span></label><div className="stack">{(["city","slogan","phone","whatsapp","address","instagram","website"] as const).map(key=><label key={key}>{{city:"Cidade",slogan:"Slogan",phone:"Telefone",whatsapp:"WhatsApp",address:"Endereço",instagram:"Instagram",website:"Site"}[key]}<input name={key} maxLength={key==="address"?400:200} defaultValue={identity?.[key]||""}/></label>)}</div><div className="token-grid">{themeKeys.map(key=><label key={key}>{labels[key]}<input type="color" value={tokens[key]} onChange={e=>setTokens({...tokens,[key]:e.target.value})}/><span className="form-note">{tokens[key]}</span></label>)}</div>{state.error&&<p role="alert" className="error">{state.error}</p>}{state.success&&<p role="status" className="message">{state.success}</p>}<Submit>Salvar identidade</Submit></form><section className="theme-preview" style={themeStyle(tokens)} aria-label="Prévia das cores"><p className="eyebrow">Prévia</p><h2>Que bom ter você aqui.</h2><div className="sample"><p>Um cuidado próximo, em cada começo.</p><p className="muted">Jornada da Gestante com sua clínica.</p><span className="button">Exemplo de botão</span></div></section></div>;
}
